#!/usr/bin/env node
const p = process.cwd();
if (process.argv.includes("metadata")) {
  console.log(JSON.stringify({
    packages: [{
      name: "app", 
      version: "0.1.0",
      id: "app 0.1.0 (path+file://" + p + ")",
      source: null,
      dependencies: [{
        name: "tauri",
        source: "registry+https://github.com/rust-lang/crates.io-index",
        req: "^2.0.0",
        kind: null,
        rename: null,
        optional: false,
        uses_default_features: true,
        features: [],
        target: null,
        registry: null
      }],
      targets: [],
      features: {},
      manifest_path: p + "/Cargo.toml"
    }],
    workspace_members: ["app 0.1.0 (path+file://" + p + ")"],
    workspace_root: p,
    target_directory: p + "/target",
    version: 1,
    workspace_default_members: ["app 0.1.0 (path+file://" + p + ")"],
    resolve: null
  }));
} else if (process.argv.includes("tauri-build")) {
} else {
  console.log("");
}
