// This script generates the Korean translation section
// Each en key is mapped to its Korean translation
const koTranslations = {
  "control_panel.title": "제어판",
  "control_panel.subtitle": "시스템 설정 및 세부 규칙 조정",
  "control_panel.check_update": "업데이트 확인",
  "control_panel.checking": "확인 중",

  "tabs.connection": "연결",
  "tabs.features": "기능",
  "tabs.persona": "페르소나",
  "tabs.storage": "저장소",

  "sandbox.title": "개발자 샌드박스",
  "sandbox.desc": "Prompt 컴파일, SSE 버퍼 파싱 및 월드북 스캔 과정을 실시간으로 확인합니다",
  "sandbox.button": "🚀 개발자 샌드박스 입장",

  "lang.section_title": "언어 설정",
  "lang.select_label": "앱 언어",
  "lang.select_desc": "인터페이스 언어를 전환합니다. 첫 실행 시 시스템 언어에 따라 자동으로 설정됩니다.",

  "features.section_title": "기능 설정",
  "features.cat_rendering": "UI 렌더링 및 인터랙션",

  "features.html_rendering": "리치 텍스트 HTML 렌더링",
  "features.html_rendering_desc": "캐릭터 카드가 HTML/CSS 태그로 대화 말풍선 스타일을 지정할 수 있도록 허용합니다. 비활성화 시 일반 텍스트로 표시됩니다.",

  "features.js_execution": "카드 JS 스크립트 실행",
  "features.js_execution_desc": "캐릭터 카드가 샌드박스 내에서 커스텀 JS를 실행하여 동적 상태 패널을 표시할 수 있도록 허용합니다. 실행에는 보안 위험이 따릅니다.",

  "features.loop_protection": "스크립트 루프 보호",
  "features.loop_protection_desc": "스크립트 루프에 워치독 타이머를 삽입하여 WebView 잠금을 방지합니다. 실행 제한: 1000ms.",

  "features.ambient_glow": "감정 앰비언트 글로우",
  "features.ambient_glow_experimental": "베타",
  "features.ambient_glow_desc": "캐릭터의 표정과 감정에 맞춰 채팅 배경에 흐르는 글로우를 렌더링하여 몰입감을 높입니다.",

  "features.reasoning_display": "추론 과정 표시",
  "features.reasoning_display_desc": "AI 응답의 사고 연쇄(reasoning_content)를 표시하거나 숨깁니다. 숨겨도 모델 생성에는 영향을 미치지 않습니다.",

  "features.message_queue": "멀티 메시지 큐",
  "features.message_queue_plugin": "플러그인",
  "features.message_queue_desc": "클릭 시 메시지를 큐에 추가만 하고 응답하지 않습니다. 500ms 이상 길게 누르면 큐에 쌓인 메시지를 병합하여 AI 응답을 트리거합니다.",

  "features.asterisk_formatting": "별표 서식",
  "features.asterisk_formatting_desc": "*동작 설명*을 부드러운 기울임꼴 회색으로 렌더링합니다. 캐릭터 비주얼 설정이 이를 덮어씁니다.",

  "features.bison_mode": "바이슨 모드",
  "features.bison_mode_token_warning": "Token 소모 증가",
  "features.bison_mode_desc": "AI가 감정에 따라 2-3개의 연속 응답을 큐에 넣고 출력합니다(각 응답 최대 100 Token).",
  "features.bison_mode_warning": "⚠️ 연속 API 요청이 발생하여 Token 소모량이 크게 증가할 수 있습니다.",
  "features.bison_mode_prompt_title": "바이슨 모드 Prompt 템플릿",
  "features.reset_default": "기본값으로 초기화",

  "features.reply_suggestions": "AI 응답 제안",
  "features.reply_suggestions_desc": "이후 스토리 분기 옵션을 생성합니다. 클릭하여 입력하거나 바로 전송할 수 있습니다.",
  "features.click_mode": "기본 클릭 동작",
  "features.click_mode_fill": "입력창에 채우기",
  "features.click_mode_send": "바로 전송",
  "features.suggestions_prompt_title": "제안 Prompt 템플릿",
  "features.expression_dict_title": "감정 매칭 정규식 사전",
  "features.expression_dict_desc": "카드에 트리거가 없을 때 감정을 매칭하는 대체 정규식입니다(비우면 비활성화).",
  "features.reset_dict": "사전 초기화",

  "report.title": "시스템 리포트",
  "report.copy": "리포트 복사",
  "report.check_start": "진단 실행",
  "report.checking": "실행 중...",

  "theme.section_title": "테마 및 색상",
  "theme.placeholder": "테마 선택",
  "theme.snow": "미니멀 화이트",
  "theme.sand": "웜 샌드",
  "theme.ocean": "딥 오션",
  "theme.obsidian": "옵시디언 블랙",
  "theme.custom_theme": "커스텀 테마",
  "theme.custom_header": "가져온 테마",
  "theme.dark": "다크",
  "theme.light": "라이트",
  "theme.management": "테마 관리",
  "theme.new": "새 테마",
  "theme.import": "테마 가져오기",
  "theme.no_custom_desc": "가져온 커스텀 테마가 없습니다. .tavern-theme.json 파일을 가져와 CSS 변수와 스타일을 커스터마이즈하세요.",
  "theme.font_size": "글꼴 크기",
  "theme.font_size_current": "글꼴 크기",
  "theme.line_height": "줄 간격",
  "theme.line_height_current": "줄 높이",
  "theme.bg_image": "기본 채팅 배경 (캐릭터 배경이 설정되지 않은 경우 활성화)",
  "theme.bg_image_enabled": "✨ 커스텀 배경 이미지 활성화됨",
  "theme.bg_image_disabled": "설정되지 않음 (기본 테마 배경 사용)",
  "theme.upload": "업로드",
  "theme.clear": "초기화",
  "theme.bg_effect": "채팅 배경 블렌드",
  "theme.effect_clear": "초기화 (원본)",
  "theme.effect_medium": "중간 (블렌드)",
  "theme.effect_dark": "어둡게 (프로스트)",
  "theme.bg_animation": "Ken Burns 효과 활성화 (슬로우 모션)",

  "nav.characters": "캐릭터",
  "nav.chat-history": "채팅",
  "nav.global-worldbook": "월드북",
  "nav.settings": "설정",

  "api.title": "API 엔드포인트 설정",
  "api.subtitle": "LLM 서비스 엔드포인트 URL 및 인증 자격 증명을 구성합니다",
  "api.saving": "자동 저장 중...",
  "api.saved": "변경 사항이 자동 저장되었습니다",
  "api.select_profile": "API 프로필 / 자격 증명 파일 선택",
  "api.temp_profile": "💡 임시 디버그 프로필",
  "api.save_profile": "현재 설정을 프로필로 저장",
  "api.rename": "✏️ 이름 변경",
  "api.delete": "🗑️ 프로필 삭제",
  "api.base_url": "기본 URL",
  "api.base_url_tip": "여러 API 기록 자동 저장 지원",
  "api.clear_history": "기록 초기화",
  "api.api_key": "API 키",
  "api.test_conn": "⚡ 연결 테스트",
  "api.fetch_models": "모델 가져오기",
  "api.fetching_models": "가져오는 중...",
  "api.free_tier": "💡 무료 티어 채널 활성화됨 ({count}/10회 사용). API 키가 비어 있을 때 활성화됩니다.",
  "api.exclusive_tier": "커스텀 API 키가 설정되어 전용 채널을 사용 중입니다.",
  "api.model_id": "모델 ID",
  "api.select_model_placeholder": "가져온 모델 선택",
  "api.context_limit": "최대 컨텍스트 제한 (Token)",
  "api.context_limit_tip": "비워두면 모델 기본 용량에 맞춥니다",
  "api.prompt_format": "Prompt 레이아웃 형식",
  "api.prompt_format_tip": "시스템 Prompt와 로어북의 구조를 정의합니다",
  "api.format_auto": "자동 선택",
  "api.format_xml": "XML 태그",
  "api.format_markdown": "Markdown 텍스트",
  "api.fallback_title": "보수적 폴백 (최소 파라미터)",
  "api.fallback_desc": "모델 유형과 관계없이 5개의 기본 파라미터(model, messages, stream, temperature, top_p)만 강제로 전송합니다. API가 HTTP 400 오류를 반환할 때 활성화하세요.",
  "api.send_names_title": "캐릭터 이름 전송",
  "api.send_names_desc": "요청 메시지에 'name' 속성을 포함합니다(예: 'user', 캐릭터 이름). Claude/Gemini에서 HTTP 400 오류 발생 시 비활성화하세요.",
  "api.disable_reasoning_title": "추론(Deep Thinking) 비활성화",
  "api.disable_reasoning_desc": "추론 모델(예: Claude 3.7 / DeepSeek R1)의 사고 Token을 절약하기 위해 API 레벨에서 추론을 강제로 비활성화합니다.",

  "image_gen.title": "AI 이미지 생성 설정",
  "image_gen.subtitle": "Stable Diffusion, NovelAI 또는 DALL-E 엔드포인트를 구성합니다",
  "image_gen.enable": "이미지 생성 활성화",
  "image_gen.enable_desc": "메시지 빠른 메뉴에서 대화 장면을 그림으로 생성할 수 있습니다.",
  "image_gen.force_protocol": "특정 프로토콜 강제",
  "image_gen.force_protocol_desc": "비활성화 시 기본 URL에서 자동 감지합니다(NovelAI/SD-WebUI 형식을 적용하고, 기본값은 OpenAI DALL-E).",
  "image_gen.protocol_title": "이미지 생성 프로토콜 유형",
  "image_gen.auto_detect": "자동 감지 모드 (URL에서 추측)",
  "image_gen.base_url": "이미지 생성 기본 URL",
  "image_gen.api_key": "API 키 / 액세스 Token",
  "image_gen.api_key_placeholder": "키 또는 액세스 Token 입력",
  "image_gen.model": "모델",
  "image_gen.model_placeholder": "예: dall-e-3 또는 custom-model",
  "image_gen.width": "너비",
  "image_gen.height": "높이",
  "image_gen.steps": "스텝",
  "image_gen.cfg": "CFG 스케일",
  "image_gen.sampler": "샘플러",
  "image_gen.sampler_placeholder": "예: Euler a",
  "image_gen.edit_before_gen": "생성 전 Prompt 편집",
  "image_gen.edit_before_gen_desc": "요청 전송 전에 Prompt 입력창을 표시하여 생성 태그를 수정할 수 있습니다.",
  "image_gen.advanced_prompts": "고급 Prompt 및 템플릿",
  "image_gen.prompt_prefix": "기본 Prompt 접두사",
  "image_gen.negative_prompt": "네거티브 Prompt",
  "image_gen.prompt_template": "Prompt 생성기 템플릿",
  "image_gen.prompt_template_desc": "요약 LLM을 위한 가이드 지침입니다. {appearance}, {context}, {message} 자리 표시자가 대체됩니다.",

  "tts.title": "Text-to-Speech (TTS)",
  "tts.enable": "TTS 음성 활성화",
  "tts.enable_desc": "빠른 동작에서 메시지 로그를 소리 내어 읽을 수 있도록 합니다",
  "tts.trigger": "트리거 모드",
  "tts.trigger_auto": "자동 읽기 (기본)",
  "tts.trigger_manual": "수동 읽기 (요청 시)",
  "tts.range": "콘텐츠 범위",
  "tts.range_all": "전체 텍스트 읽기 (동작 포함)",
  "tts.range_dialogue": "대사만 읽기 (동작 제외)",
  "tts.engine": "음성 엔진 (제공자)",
  "tts.engine_system": "시스템 내장 TTS (로컬 합성)",
  "tts.engine_openai": "OpenAI TTS API (온라인 고품질)",
  "tts.volume": "볼륨",
  "tts.rate": "속도",
  "tts.pitch": "피치",
  "tts.system_desc": "모바일 클라이언트는 시스템 내장 TTS 엔진을 사용하며, 음성은 시스템 설정에 따라 결정됩니다.",
  "tts.voice": "음성 역할",
  "tts.test_play": "음성 테스트",
  "tts.test_stop": "테스트 중지",

  "asr.title": "음성 인식 (ASR)",
  "asr.subtitle": "마이크 입력 및 음성-텍스트 변환을 활성화합니다 (WebSpeech 또는 OpenAI Whisper)",
  "asr.enable": "음성 입력 활성화",
  "asr.enable_desc": "채팅 입력 영역 옆에 마이크 버튼을 표시하여 음성을 녹음하고 텍스트로 변환합니다.",
  "asr.engine": "음성 인식 제공자",
  "asr.engine_system": "시스템 내장 Web Speech API (무료 / 실시간 스트리밍)",
  "asr.engine_whisper": "OpenAI Whisper API (고정확도)",
  "asr.lang": "언어",
  "asr.lang_placeholder": "예: en-US, zh-CN, ja-JP, ko-KR",
  "asr.lang_desc": "Web Speech에 필요한 언어 식별자입니다. Whisper는 비워두면 자동 감지할 수 있습니다.",

  "persona.title": "사용자 페르소나",
  "persona.active": "활성 사용자 페르소나",
  "persona.select_placeholder": "페르소나 선택...",
  "persona.unnamed": "이름 없는 캐릭터",
  "persona.create": "생성",
  "persona.delete": "삭제",
  "persona.name": "플레이어 이름 (LLM 치환에 사용됨)",
  "persona.name_placeholder": "이름 모를 여행자",
  "persona.avatar": "플레이어 커스텀 아바타 (Base64)",
  "persona.avatar_placeholder": "data:image/png;base64,... 또는 비워둠",
  "persona.upload": "업로드",
  "persona.clear": "초기화",
  "persona.desc": "플레이어 배경 (페르소나 설명)",
  "persona.desc_placeholder": "예: 키 180cm, 검은 트렌치코트 착용, 차분한 시선...",

  "memory_sys.title": "메모리 시스템",
  "memory_sys.subtitle": "단기 윈도우, 서사 타임라인 요약 및 구조적 테이블 메모리를 함께 관리합니다",
  "memory_sys.recent_turns_title": "컨텍스트 윈도우",
  "memory_sys.recent_turns": "컨텍스트 최근 턴",
  "memory_sys.recent_turns_desc": "Prompt 컨텍스트에 직접 유지되는 대화 라운드 수",
  "memory_sys.recall_title": "장기 리콜",
  "memory_sys.recall_enable": "메모리 리콜 활성화",
  "memory_sys.recall_desc": "벡터 저장소에서 유사한 과거 이벤트를 자동으로 쿼리합니다",
  "memory_sys.recall_top_k": "리콜 Top K 개수",
  "memory_sys.summary_title": "서사 메모리 (자동 요약)",
  "memory_sys.summary_enable": "자동 요약 활성화",
  "memory_sys.summary_desc": "주기적인 백그라운드 요약을 트리거합니다 (0은 컨텍스트 턴과 일치)",
  "memory_sys.summary_trigger": "트리거 턴 (요약 간 라운드 수, 0은 컨텍스트 턴과 일치)",
  "memory_sys.table_title": "상태 메모리 (테이블 메모리)",
  "memory_sys.table_enable": "테이블 메모리 활성화",
  "memory_sys.table_desc": "호감도 및 캐릭터 관계를 구조적 Markdown 테이블로 저장합니다",
  "memory_sys.table_freq": "AI 테이블 업데이트 빈도 (업데이트 간 라운드 수)",
  "memory_sys.table_freq_1": "1 라운드마다 (가장 실시간)",
  "memory_sys.table_freq_3": "3 라운드마다 (권장)",
  "memory_sys.table_freq_5": "5 라운드마다 (Token 절약)",
  "memory_sys.advanced_title": "고급 템플릿 및 Prompt",
  "memory_sys.time_tag": "시간 태그 템플릿",
  "memory_sys.time_tag_desc": "{{index}}를 요약 단계 번호 지정용 자리 표시자로 사용하세요",
  "memory_sys.summary_prompt": "요약 시스템 Prompt",
  "memory_sys.reset_summary": "요약 Prompt를 기본값으로 초기화",
  "memory_sys.reasoning_prompt": "추론 가이드 Prompt",
  "memory_sys.reset_reasoning": "추론 Prompt를 기본값으로 초기화",
  "memory_sys.table_prompt": "테이블 메모리 Prompt",
  "memory_sys.reset_table": "테이블 Prompt를 기본값으로 초기화",

  "backup.title": "백업 및 마이그레이션",
  "backup.subtitle": "설정, 카드 및 로그를 내보내거나 데이터베이스 백업에서 복원합니다",
  "backup.export_btn": "JSON 백업 내보내기",
  "backup.import_btn": "가져오기 및 복원",
  "backup.pass_title": "독립 암호화 비밀번호",
  "backup.pass_tip": "강력히 권장합니다. 데이터 유출을 방지하기 위해 강력하게 암호화됩니다",
  "backup.encrypt_switch": "이 백업 데이터를 강제 암호화",
  "backup.status_idle": "활성 백업/복원 작업 없음",

  "chat_import.title": "채팅 기록 가져오기",
  "chat_import.subtitle": "SillyTavern 단일 캐릭터 채팅 로그(.json/.jsonl) 형식 파일을 가져옵니다",
  "chat_import.upload_btn": "채팅 파일 선택 및 가져오기",

  "telemetrics.title": "사용 통계 (Telemetrics)",
  "telemetrics.subtitle": "기본 실행 로그 (번들 텔레메트리 추적용)",
  "telemetrics.total_opens": "총 실행 횟수",
  "telemetrics.total_runtime": "총 실행 시간",
  "telemetrics.times": "{count}회",
  "telemetrics.minutes": "{count}분",

  "samplers.title": "Temperature 및 샘플링 파라미터",
  "samplers.subtitle": "모델 생성을 위한 무작위성, 페널티 및 최대 Token 제한을 조정합니다",
  "samplers.temp": "Temperature (Temp)",
  "samplers.top_p": "Nucleus 샘플링 (Top P)",
  "samplers.rep_penalty": "반복 페널티",
  "samplers.max_tokens": "최대 Token",

  "preset_selector.active_preset": "활성 프리셋: {name}",
  "preset_selector.import": "설정 가져오기",
  "preset_selector.export": "설정 내보내기",
  "preset_selector.save_copy": "복사본 저장",
  "preset_selector.delete_custom": "커스텀 프리셋 삭제",

  "prompts.title": "프리셋 Prompt 설정",
  "prompts.subtitle": "기본 시스템 Prompt, 탈옥 및 커스텀 모듈을 구성합니다",
  "prompts.st_compat_desc": "ST 매크로 지원: {{char}}, {{user}}가 동적으로 치환됩니다.",
  "prompts.confirm_delete": "삭제 확인",
  "prompts.cancel": "취소",
  "prompts.batch_delete": "일괄 삭제",
  "prompts.create_module": "새 모듈",
  "prompts.no_modules": "활성 모듈 없음",
  "prompts.system_prompt": "시스템 Prompt",
  "prompts.system_prompt_tip": "system · 컨텍스트 상단에 배치됨",
  "prompts.system_prompt_placeholder": "롤플레잉 지침을 여기에 입력하세요...",
  "prompts.jailbreak": "탈옥 Prompt",
  "prompts.jailbreak_tip": "system · 마지막 메시지 전에 주입됨",
  "prompts.jailbreak_placeholder": "탈옥 규칙을 여기에 입력하세요...",

  "regex.title": "정규식 필터",
  "regex.subtitle": "표시 전에 입출력 메시지를 정제하는 정규식 스크립트를 구성합니다",
  "regex.global": "🌌 전역 정규식",
  "regex.global_tip": "모든 캐릭터와 프리셋에 적용되며 전역으로 저장됩니다",
  "regex.preset": "📋 프리셋 정규식",
  "regex.preset_tip": "프리셋 [{name}]이 활성화된 경우에만 적용되며 프리셋과 함께 내보내집니다",
  "regex.char": "🎭 캐릭터 로컬 정규식",
  "regex.char_tip": "[{name}]이 로드된 경우에만 적용되며 캐릭터 카드에 저장됩니다",
  "regex.create_global": "새 전역",
  "regex.create_preset": "새 프리셋",
  "regex.create_char": "새 캐릭터",
  "regex.no_global": "전역 정규식 규칙이 없습니다. <think> 태그 필터를 추가하려면 클릭하세요.",
  "regex.no_preset": "프리셋 정규식 규칙이 없습니다. 프리셋 가져오기 시 자동으로 로드됩니다.",
  "regex.no_char": "이 캐릭터에 대한 로컬 정규식 규칙이 없습니다. 생성하려면 클릭하세요.",
  "regex.placement_both": "모두",
  "regex.placement_input": "입력",
  "regex.placement_output": "출력",
  "regex.edit": "편집",
  "regex.delete": "삭제",
  "regex.modal_new": "새 정규식 스크립트",
  "regex.modal_edit": "정규식 스크립트 편집",
  "regex.modal_close": "닫기",
  "regex.modal_name": "스크립트 이름",
  "regex.modal_name_placeholder": "예: 사고 과정 숨기기",
  "regex.modal_find": "매칭 정규식 패턴 (/pattern/flags 지원)",
  "regex.modal_find_placeholder": "예: /<think>[\\s\\S]*?<\\/think>/gi",
  "regex.modal_replace": "대체 문자열 ($1, $2 지원)",
  "regex.modal_replace_placeholder": "예: (비워두면 매치된 부분 제거)",
  "regex.modal_placement": "적용 위치",
  "regex.modal_placement_input": "입력 단계 (전송 전)",
  "regex.modal_placement_output": "출력 단계 (표시 전)",
  "regex.modal_save": "저장",

  "preset_form.none": "없음",
  "preset_form.scope_global": "전역",
  "preset_form.scope_preset": "프리셋",
  "preset_form.scope_char": "캐릭터",
  "preset_form.confirm_delete_regex": "{scope} 정규식 스크립트 '{name}'을(를) 삭제하시겠습니까?",
  "preset_form.regex_empty_error": "스크립트 이름과 정규식 패턴은 비워둘 수 없습니다!",
  "preset_form.confirm_batch_delete_prompts": "선택한 {count}개의 Prompt 모듈을 일괄 삭제하시겠습니까?",
  "preset_form.confirm_batch_delete_global_regex": "선택한 {count}개의 전역 정규식 스크립트를 일괄 삭제하시겠습니까?",
  "preset_form.confirm_batch_delete_preset_regex": "선택한 {count}개의 프리셋 정규식 스크립트를 일괄 삭제하시겠습니까?",

  "worldbook.title": "월드북",
  "worldbook.subtitle": "전용 캐릭터 바운드 / 전역 공유",
  "worldbook.new": "새로 만들기",
  "worldbook.import": "가져오기",
  "worldbook.export": "내보내기",
  "worldbook.export_alert": "내보내기 전에 먼저 월드북(전역 또는 캐릭터)을 선택해 주세요.",
  "worldbook.list_header": "👤 캐릭터 바운드 월드북",
  "worldbook.list_count": "총 {count}개",
  "worldbook.custom_tip": "🔒 독립 월드북 (길게 눌러 삭제)",
  "worldbook.no_characters": "📭 캐릭터 카드를 찾을 수 없습니다. 설정 탭에서 캐릭터 카드를 생성하여 캐릭터 바운드 월드북을 해제하세요!",
  "worldbook.char_tip_global": "🌎 월드북이 [전역 공유]로 설정됨",
  "worldbook.char_tip_local": "🔒 월드북이 [캐릭터 바운드]로 설정됨",
  "worldbook.switch_global": "🌎 전역",
  "worldbook.switch_local": "👤 바운드",

  "history.title": "기록",
  "history.sort_by_time": "타임라인",
  "history.sort_by_char": "캐릭터별",
  "history.empty": "채팅 기록을 찾을 수 없습니다",
  "history.empty_tip": "캐릭터를 선택하여 채팅을 시작하세요!",
  "history.main_timeline": "메인 타임라인",
  "history.turns_chars": "{turnCount}턴 | {charCount}자",
  "history.turns": "{count}턴",
  "history.chars": "{count}자",
  "history.me": "나",
  "history.delete": "채팅 삭제",
  "history.sessions_count": "{count}개 채팅",
  "history.recent_active": "마지막 활동: {time}",
  "history.total_chars": "총 {count}자",
  "history.unassigned_char": "할당되지 않은 캐릭터",
  "history.removed_char": "삭제된 캐릭터",

  "scanner.title": "로컬 캐릭터 카드 스캔 및 가져오기",
  "scanner.close": "닫기",
  "scanner.scan_failed": "스캔 실패: ",
  "scanner.import_success": "가져오기 성공: \"{name}\" 카드가 로드되었습니다!",
  "scanner.import_failed": "파일 가져오기 실패: ",
  "scanner.mock_env": "브라우저 샌드박스 환경",
  "scanner.mock_env_tip": "현재 웹 개발 모드에서 실행 중입니다. 인터페이스 상호작용과 카드 파싱을 테스트하려면 아래 버튼을 클릭하여 시뮬레이션된 캐릭터 카드를 로드할 수 있습니다.",
  "scanner.mock_scanning": "스캔 시뮬레이션 중...",
  "scanner.mock_btn": "모의 저장소 스캔 (파일 스캔)",
  "scanner.permission_title": "저장소 액세스 권한 필요",
  "scanner.permission_desc": "앱이 캐릭터 카드를 찾기 위해 외부 저장소(예: 다운로드 디렉터리)에 액세스해야 합니다. 기기 설정에서 언제든지 이 권한을 전환하거나 취소할 수 있습니다.",
  "scanner.permission_btn": "권한 부여 및 저장소 스캔",
  "scanner.scanning": "저장소 미디어 검색 중...",
  "scanner.scan_btn": "다운로드 및 사진 디렉터리 스캔",
  "scanner.search_placeholder": "스캔된 로컬 파일 검색...",
  "scanner.scan_waiting": "기기의 공용 디렉터리를 스캔 중입니다. 잠시만 기다려 주세요...",
  "scanner.no_results": "결과를 찾을 수 없습니다",
  "scanner.no_match": "검색어와 일치하는 파일이 없습니다.",
  "scanner.no_results_tip": "위의 스캔 버튼을 클릭하여 기기에서 .json 캐릭터 패키지 또는 Tavern PNG 카드 파일을 찾으세요.",
  "scanner.file_meta": "크기: {size} | 수정일: {date}",
  "scanner.importing": "가져오는 중",
  "scanner.import": "가져오기",

  "quick_dialogue.copy": "복사",
  "quick_dialogue.edit": "편집",
  "quick_dialogue.img_gen_not_enabled": "먼저 설정에서 이미지 생성을 활성화하고 API 파라미터를 구성해 주세요.",
  "quick_dialogue.edit_prompt_message": "이미지 Prompt가 생성되었습니다. 여기에서 수정할 수 있습니다:",
  "quick_dialogue.prompt_confirm_title": "Prompt 확인",
  "quick_dialogue.img_gen_failed": "이미지 생성 실패",
  "quick_dialogue.img_gen_failed_msg": "그리기 실패: {error}",
  "quick_dialogue.img_gen": "이미지 생성",
  "quick_dialogue.img_gen_title": "현재 대화 장면의 일러스트 생성",
  "quick_dialogue.tts_stop": "중지",
  "quick_dialogue.tts_read": "읽어주기",
  "quick_dialogue.tts_stop_title": "TTS 중지",
  "quick_dialogue.tts_read_title": "현재 대사 TTS 읽기",
  "quick_dialogue.more": "더보기",
  "quick_dialogue.more_title": "더 많은 옵션",
  "quick_dialogue.reroll": "재생성",
  "quick_dialogue.branch": "분기",
  "quick_dialogue.confirm_delete_msg": "이 단일 대사 줄을 삭제하시겠습니까?",
  "quick_dialogue.delete": "삭제",
  "quick_dialogue.confirm_summarize": "AI 카드 압축을 시작하시겠습니까? 이전 채팅 기록을 단일 타임라인 연대기로 변환하여 메모리를 확보하고 서사 일관성을 유지합니다.",
  "quick_dialogue.summarize": "요약",

  "message_bubble.user_said": "내가 말함",
  "message_bubble.char_said": "이(가) 말함",
  "message_bubble.role": "캐릭터",
  "message_bubble.me_avatar": "나",
  "message_bubble.ai_fallback": "AI",
  "message_bubble.swipe_edit": "편집",
  "message_bubble.swipe_draw": "이미지 생성",
  "message_bubble.swipe_tts_stop": "중지",
  "message_bubble.swipe_tts_read": "읽어주기",
  "message_bubble.edit_save": "저장",
  "message_bubble.edit_cancel": "취소",
  "message_bubble.reasoning_collapse": "추론 접기",
  "message_bubble.reasoning_thinking": "AI가 생각 중입니다 (탭하여 보기)...",
  "message_bubble.reasoning_view": "추론 보기",
  "message_bubble.reasoning_chars": "{length}자",
  "message_bubble.copy_reasoning": "추론 내용 복사",
  "message_bubble.ai_composing": "AI가 작성 중입니다...",
  "message_bubble.no_content": "*(생성된 콘텐츠 없음)*",
  "message_bubble.drawing_scene": "AI가 장면을 그리고 있습니다...",
  "message_bubble.confirm_save_image": "생성된 이미지를 저장하시겠습니까?",
  "message_bubble.image_save_success": "저장 성공",
  "message_bubble.image_save_success_msg": "📂 이미지가 성공적으로 저장되었습니다!\n파일이 /Download 폴더에 저장되었습니다...",
  "message_bubble.image_save_failed": "저장 실패",
  "message_bubble.image_save_failed_msg": "❌ 이미지 저장 실패: {error}",
  "message_bubble.save_error": "저장 오류",
  "message_bubble.export_success": "내보내기 성공",
  "message_bubble.click_to_save": "탭하여 이미지 저장",
  "message_bubble.round_label": "라운드 {roundNum}",

  "chat_input.reroll_last": "마지막 스토리라인 다시 불러오기",
  "chat_input.continue": "계속",
  "chat_input.suggestions_label": "✨ 서사 분기 생성기:",
  "chat_input.click_mode": "클릭 동작: {mode}",
  "chat_input.click_mode_send": "바로 전송",
  "chat_input.click_mode_fill": "입력창에 채우기",
  "chat_input.placeholder_bison": "{name}이(가) 계속 말하는 중...",
  "chat_input.placeholder_recording": "음성 입력 대기 중, 말씀해 주세요...",
  "chat_input.placeholder_transcribing": "음성을 텍스트로 변환 중...",
  "chat_input.placeholder_default": "{name}에게 메시지를 보내 시작하세요...",
  "chat_input.aria_label": "{name}에게 보내는 메시지 입력",
  "chat_input.stop": "생성 중지",
  "chat_input.asr_stop": "녹음 중지",
  "chat_input.asr_recognizing": "음성 인식 중",
  "chat_input.asr_mic": "음성 입력",
  "chat_input.asr_transcribing": "변환 중...",
  "chat_input.send_title": "메시지 전송 (길게 누르면 병합)",
  "chat_input.send": "메시지 전송",
  "chat_input.send_long_press": "탭하여 전송, 500ms 길게 누르면 이전 메시지와 병합",
  "chat_input.asr_permission_denied": "권한 오류",
  "chat_input.asr_permission_msg": "마이크 권한이 거부되었습니다. 시스템 설정에서 마이크 액세스를 허용해 주세요.",
  "chat_input.asr_no_speech": "음성이 감지되지 않음",
  "chat_input.asr_no_speech_msg": "음성 입력이 감지되지 않았습니다. 다시 시도해 주세요.",
  "chat_input.asr_device_error": "장치 오류",
  "chat_input.asr_device_error_msg": "오디오 장치 오류: {error}",
  "chat_input.asr_error": "인식 오류",
  "chat_input.asr_error_msg": "음성 인식 알 수 없는 오류: {error}",
  "chat_input.token_prediction": "예측:",

  "chat_header.back_aria": "캐릭터 목록으로 돌아가기",
  "chat_header.view_char_detail": "캐릭터 카드 상세 보기",
  "chat_header.branch_management": "분기 관리",
  "chat_header.rename_prompt": "IndexedDB 분기 구분을 위한 현재 분기 제목 편집:",
  "chat_header.click_to_edit": "(탭하여 편집)",
  "chat_header.bgm_unmute": "BGM 음소거 해제",
  "chat_header.bgm_mute": "BGM 음소거",
  "chat_header.memory_center": "메모리 및 상태 센터",
  "chat_header.memory": "메모리",
  "chat_header.timeline": "타임라인",
  "chat_header.table": "상태 데이터",
  "chat_header.dict": "메모리 사전",

  "char_detail.greeting_updated": "인사말이 성공적으로 업데이트되었습니다!",
  "char_detail.greeting_error": "인사말 설정 실패: {error}",
  "char_detail.unknown_creator": "시스템 프리셋 / 알 수 없는 제작자",
  "char_detail.tab_persona": "페르소나",
  "char_detail.tab_dialogue": "대화 스크립트",
  "char_detail.tab_lore": "월드 로어 ({count})",
  "char_detail.section_personality": "성격 특성 (Personality)",
  "char_detail.no_personality": "특정 성격이 설정되지 않았습니다...",
  "char_detail.section_description": "외모 및 배경 (Description)",
  "char_detail.no_description": "배경 스토리가 없습니다...",
  "char_detail.section_creator_notes": "제작자 노트",
  "char_detail.section_scenario": "시나리오 및 무대 설정 (Scenario)",
  "char_detail.section_examples": "대화 예시",
  "char_detail.greeting_selector_title": "인사말 장면 선택 ({count}개 사용 가능)",
  "char_detail.default_greeting": "기본 인사말",
  "char_detail.greeting_branch": "인사말 분기 {idx}",
  "char_detail.default_greeting_badge": "기본 스토리라인 오프닝",
  "char_detail.alternate_greeting_badge": "대체 장면 분기 {idx}",
  "char_detail.copy": "복사",
  "char_detail.copy_text": "전체 텍스트 복사",
  "char_detail.set_primary_greeting": "기본 인사말로 설정",
  "char_detail.set_primary_greeting_title": "이 인사말을 메인 오프닝 대사로 영구 설정",
  "char_detail.no_greeting": "(인사말이 설정되지 않음)",
  "char_detail.lore_search_placeholder": "키워드, 트리거 또는 로어 설명 검색...",
  "char_detail.clear_search": "초기화",
  "char_detail.badge_constant": "상시",
  "char_detail.badge_disabled": "비활성화",
  "char_detail.lore_empty": "이 캐릭터 카드에는 내장된 월드 로어 항목이 없습니다.",
  "char_detail.lore_no_match": "이 키워드와 일치하는 로어 항목을 찾을 수 없습니다.",
  "char_detail.priority": "우선순위:",
  "char_detail.probability": "확률:",
  "char_detail.depth": "깊이:",
  "char_detail.position": "위치:",

  "characters_tab.subtitle": "경량 모바일 롤플레잉 프론트엔드",
  "characters_tab.scan_title": "로컬 캐릭터 카드 스캔",
  "characters_tab.import_title": "SillyTavern 캐릭터 카드 가져오기",
  "characters_tab.create_title": "새 캐릭터 카드 생성",
  "characters_tab.more_title": "더 많은 작업",
  "characters_tab.no_description": "설명을 사용할 수 없습니다...",
  "characters_tab.branch_count": "{count}개 분기",
  "characters_tab.empty_title": "로컬 데이터베이스가 비어 있습니다",
  "characters_tab.empty_desc": "기존 SillyTavern 호환 PNG 캐릭터 카드를 업로드하거나 오른쪽 상단 버튼을 탭하여 수동으로 새 세계를 만드세요.",
  "characters_tab.action_subtitle": "이 캐릭터에 대한 작업 선택",
  "characters_tab.view_profile": "프로필 보기",
  "characters_tab.edit_character": "캐릭터 편집",
  "characters_tab.go_worldbook": "월드북으로 이동",
  "characters_tab.confirm_export_json": "JSON 캐릭터 카드를 내보내시겠습니까?",
  "characters_tab.export_json": "JSON으로 내보내기",
  "characters_tab.export_png": "SillyTavern PNG 카드로 내보내기",
  "characters_tab.delete_char": "이 캐릭터 삭제",

  "session_manager.title": "세션 분기 관리",
  "session_manager.busy_switch_warning": "생성이 진행 중입니다. 분기를 전환하기 전에 완료될 때까지 기다리거나 수동으로 중지해 주세요.",
  "session_manager.default_branch_name": "메인 스토리라인",
  "session_manager.user_label": "나",
  "session_manager.turn_summary_format": "{turnCount}턴 | {summaryCount}개 요약",
  "session_manager.busy_delete_warning": "생성이 진행 중입니다. 분기를 삭제하기 전에 완료될 때까지 기다리거나 수동으로 중지해 주세요.",
  "session_manager.delete_branch": "분기 삭제",
  "session_manager.busy_create_warning": "생성이 진행 중입니다. 분기를 생성하기 전에 완료될 때까지 기다리거나 수동으로 중지해 주세요.",
  "session_manager.new_branch": "새 빈 분기",

  "dialog.cancel": "취소",
  "dialog.confirm": "확인",
  "dialog.alert_default_title": "알림",
  "dialog.confirm_default_title": "확인",
  "dialog.prompt_default_title": "입력",

  "recall_tab.info": "💡 마지막 메시지에서 AI가 성공적으로 검색한 **컨텍스트 메모리**를 보여줍니다. 의미적 유사도 검색(유사도 임계값 > 0.7)을 기반으로 장기 메모리 참조로 주입되었습니다.",
  "recall_tab.empty_title": "이번 라운드에 검색된 메모리 없음",
  "recall_tab.empty_desc": "현재 주제가 어떤 사전 엔티티나 과거 메모리 요약과도 일치하지 않았음을 의미합니다. 메모리 사전에 수동으로 새 키 엔티티 항목을 추가하거나, 더 많은 대화가 축적된 후 AI가 자동 요약할 때까지 기다리세요.",
  "recall_tab.turn_label": "턴 {turn}",
  "recall_tab.role_user": "사용자",
  "recall_tab.role_char": "캐릭터",
  "recall_tab.unpin": "고정 해제",
  "recall_tab.pin": "강제 고정",
  "recall_tab.unmute": "음소거 해제",
  "recall_tab.mute": "강제 음소거",
  "recall_tab.hit_tags": "히트 태그:",

  "dict_tab.type_all": "전체",
  "dict_tab.type_character": "캐릭터",
  "dict_tab.type_location": "장소",
  "dict_tab.type_item": "아이템",
  "dict_tab.type_organization": "조직",
  "dict_tab.type_concept": "개념",
  "dict_tab.entity_name_required": "엔티티 이름은 비워둘 수 없습니다!",
  "dict_tab.duplicate_entity": "\"{name}\" 이름의 엔티티가 이미 존재합니다. 중복 추가하지 마세요.",
  "dict_tab.confirm_delete_entry": "메모리 항목 \"{entity}\"의 물리적 삭제를 확인하시겠습니까?\n이 작업은 되돌릴 수 없으며 향후 장기 메모리 리콜 정확도에 영향을 미칠 수 있습니다.",
  "dict_tab.info": "메모리 사전은 장기 리콜을 위한 메타데이터 캐시입니다. 캐릭터, 장소 또는 핵심 개념을 정의할 때마다 AI는 이를 단서로 사용하여 의미적으로 유사한 메모리를 자동 검색하고 후속 대화에서 보상적으로 주입합니다.",
  "dict_tab.search_placeholder": "엔티티 이름 또는 별칭 검색...",
  "dict_tab.close_form": "새 항목 폼 닫기",
  "dict_tab.add_entry": "수동으로 항목 추가",
  "dict_tab.form_name_label": "엔티티 이름 *",
  "dict_tab.form_name_placeholder": "예: 백발의 예언자 에드가",
  "dict_tab.form_aliases_label": "별칭 (쉼표로 구분된 키워드)",
  "dict_tab.form_aliases_placeholder": "에드가, 예언자, 올드 에드",
  "dict_tab.form_type_label": "엔티티 유형 *",
  "dict_tab.cancel": "취소",
  "dict_tab.saving": "저장 중",
  "dict_tab.confirm_save": "저장 확인",
  "dict_tab.loading": "메모리 사전 불러오는 중...",
  "dict_tab.empty_title": "📭 메모리 사전이 아직 구축되지 않음",
  "dict_tab.empty_desc": "캐릭터, 장소 또는 중요한 아이템과 같은 핵심 개념 엔티티를 추가하세요. AI는 후속 대화에서 정의된 메모리 키를 자동으로 검색하여 서사 일관성을 유지합니다.",
  "dict_tab.start_adding": "✨ 첫 메모리 엔티티 추가 시작하기",
  "dict_tab.edit_entry": "메모리 항목 \"{entity}\" 편집",
  "dict_tab.no_match": "일치하는 항목 없음",
  "dict_tab.no_match_tip_filter": "필터 조건을 변경하거나 검색어를 초기화해 보세요.",
  "dict_tab.no_match_tip_empty": "캐릭터와의 대화가 늘어나면 AI가 자동으로 가치 있는 명사 엔티티를 추출해 드립니다.",
  "dict_tab.mention_count": "{count}회 언급됨",
  "dict_tab.aliases_label": "별칭:",
  "dict_tab.no_aliases": "별칭 없음",
  "dict_tab.view_detail": "상세 보기",
  "dict_tab.edit_aliases": "별칭 편집",
  "dict_tab.delete_entry_title": "항목 삭제",
  "dict_tab.detail_first_seen": "첫 등장 턴:",
  "dict_tab.detail_manual": "수동 생성됨",
  "dict_tab.detail_turn": "턴 {turn}",
  "dict_tab.detail_created": "생성일:",
  "dict_tab.detail_updated": "마지막 업데이트:",
  "dict_tab.edit_placeholder": "쉼표 또는 공백으로 구분된 별칭, 예: 문파주, 사형",
  "dict_tab.save": "저장",
  "dict_tab.new_entry_title": "새 메모리 항목",
  "dict_tab.export_dict": "사전 내보내기",
  "dict_tab.export_dict_title": "현재 세션 사전 내보내기",

  "table_memory.confirm_delete_row": "이 행을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
  "table_memory.confirm_reset": "현재 테이블 데이터를 모두 지우고 기본 4개 테이블(관계, 아이템, 장소, 퀘스트)로 초기화합니다. 이 작업은 되돌릴 수 없습니다. 계속하시겠습니까?",
  "table_memory.confirm_delete_sheet": "\"{name}\" 테이블과 모든 데이터를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
  "table_memory.min_one_column": "최소 하나의 열이 필요합니다",
  "table_memory.name_required": "테이블 이름은 비워둘 수 없습니다",
  "table_memory.columns_required": "최소 하나의 열이 필요합니다",
  "table_memory.duplicate_name": "\"{name}\" 이름의 테이블이 이미 존재합니다. 다른 이름을 사용해 주세요.",
  "table_memory.manage": "⚙️ 관리",
  "table_memory.new_table": "새 테이블",
  "table_memory.edit_table": "테이블 구조 편집",
  "table_memory.cancel": "취소",
  "table_memory.form_name_label": "테이블 이름 *",
  "table_memory.form_name_placeholder": "예: 호감도 관계",
  "table_memory.form_columns_label": "열 이름 (쉼표로 구분, 첫 번째가 기본 키)",
  "table_memory.form_columns_placeholder": "이름, 호감도, 관계",
  "table_memory.column_edit_tip": "현재는 열 이름을 편집하여 구조만 조정할 수 있습니다. 기존 데이터는 지워지지 않습니다.",
  "table_memory.save": "저장",
  "table_memory.reset_default": "기본 테이블 초기화",
  "table_memory.new_custom": "새 커스텀 테이블",
  "table_memory.empty": "구조화된 테이블 없음",
  "table_memory.init_defaults": "기본 테이블 초기화",
  "table_memory.enabled": "Prompt 주입 활성화됨",
  "table_memory.disabled": "주입 비활성화됨",
  "table_memory.delete_table": "전체 테이블 삭제",
  "table_memory.init_required": "먼저 테이블 메모리를 초기화해 주세요",
  "table_memory.one_click_init": "원클릭 초기화",
  "table_memory.no_rows": "아직 레코드가 없습니다. 아래 추가 버튼을 탭하여 새 행을 삽입하세요.",
  "table_memory.empty_cell": "비어 있음",
  "table_memory.delete_row": "이 행 삭제",
  "table_memory.add_row": "새 행 추가",

  "memory_drawer.title": "메모리 및 상태 센터",
  "memory_drawer.tab_timeline": "타임라인",
  "memory_drawer.tab_table": "상태 데이터",
  "memory_drawer.tab_dict": "메모리 사전",
  "memory_drawer.tab_recall": "리콜된 메모리",
  "memory_drawer.tab_mvu": "캐릭터 변수",
  "memory_drawer.mvu_save_success": "캐릭터 변수가 성공적으로 저장 및 동기화되었습니다!",

  "app.kernel_init_failed_title": "🚨 코어 엔진 콜드 스타트 실패",
  "app.kernel_init_failed_desc": "핵심 치명적 서비스(예: 로컬 데이터베이스) 초기화 오류. 묵시적 읽기/쓰기 데이터 손상을 방지하기 위해 시스템이 차단되었습니다.",
  "app.kernel_retry_button": "🔄 콜드 스타트 재시도",

  "chat.load_sessions_failed": "채팅 세션 로드 실패: {error}",
  "chat.load_more_sessions_failed": "더 많은 채팅 세션 로드 실패: {error}",
  "chat.save_session_failed": "채팅 세션 저장 실패: {error}",
  "chat.load_more_messages_failed": "이전 메시지 로드 실패: {error}",
  "chat.delete_session_failed": "채팅 세션 삭제 실패: {error}",

  "splash.tagline": "당신의 영혼의 교향곡을 시작하세요",
  "db.writing_overlay": "데이터베이스에 쓰는 중",

  "update.new_version_title": "✨ 새 버전 v{version} 발견",
  "update.downloading": "보안 다운로드 채널 초기화 중...",
  "update.download_now": "지금 다운로드",
  "update.later": "나중에",
  "update.close_aria": "업데이트 알림 닫기",

  "settings.update_service_not_ready": "UpdateCheckService가 준비되지 않았습니다. 나중에 다시 시도해 주세요.",
  "settings.already_latest": "이미 최신 버전입니다",
  "settings.already_latest_message": "현재 v{version}이(가) 최신 버전입니다.",
  "settings.check_failed": "확인 실패",
  "settings.check_failed_message": "업데이트 확인 중 오류 발생: {error}",

  "character_editor.modal_title_edit": "SillyTavern 호환 카드 라이브러리 편집",
  "character_editor.modal_title_create": "AI 소울 컨테이너 설정 재구축",
  "character_editor.tab_detail": "1. 캐릭터 성격 및 기본 정보",
  "character_editor.tab_lore": "2. 캐릭터 전용 월드북 바인딩 ({count})",
  "character_editor.cancel_button": "변경 사항 폐기",
  "character_editor.save_button": "변경 사항 저장",
  "character_editor.confirm_delete": "이 캐릭터 카드를 삭제하시겠습니까? 모든 파생 채팅 기록과 월드북이 정리됩니다.",
  "character_editor.name_required": "캐릭터 이름을 입력해 주세요",
  "character_editor.save_failed": "캐릭터 저장 실패: {error}",
  "character_editor.lore_content_required": "월드북 항목 콘텐츠는 비워둘 수 없습니다",
  "character_editor.lore_save_failed": "로어 저장 실패: {error}",

  "char_detail_tab.label_name": "캐릭터 이름 *",
  "char_detail_tab.placeholder_name": "예: Aria",
  "char_detail_tab.label_avatar": "아바타 URL (base64 또는 온라인 이미지 지원)",
  "char_detail_tab.placeholder_avatar": "data:image/png;base64,... 또는 http://...",
  "char_detail_tab.upload": "업로드",
  "char_detail_tab.avatar_too_large": "⚠️ 업로드 실패: 아바타 이미지 크기는 5MB를 초과할 수 없습니다!",
  "char_detail_tab.compress_failed": "⚠️ 이미지 압축 실패: {error}",
  "char_detail_tab.label_bg": "커스텀 채팅 배경 이미지 (base64 또는 온라인 이미지 지원, 우선 렌더링됨)",
  "char_detail_tab.placeholder_bg": "설정되지 않음 (전역 배경 또는 기본 테마 색상 사용)",
  "char_detail_tab.bg_too_large": "⚠️ 업로드 실패: 배경 이미지 크기는 5MB를 초과할 수 없습니다!",
  "char_detail_tab.clear": "초기화",
  "char_detail_tab.label_asterisk": "별표 동작 색상 렌더링 (캐릭터 레벨 덮어쓰기)",
  "char_detail_tab.asterisk_inherit": "전역 설정 따르기",
  "char_detail_tab.asterisk_enable": "강제 활성화",
  "char_detail_tab.asterisk_disable": "강제 비활성화",
  "char_detail_tab.label_description": "캐릭터 설명 (Description/Persona)",
  "char_detail_tab.placeholder_description": "상세 설명, 성격 또는 배경 설정...",
  "char_detail_tab.label_personality": "성격 세부 설정 (Personality Description)",
  "char_detail_tab.placeholder_personality": "캐릭터의 핵심 성격 특성",
  "char_detail_tab.label_scenario": "현재 시나리오 컨텍스트",
  "char_detail_tab.placeholder_scenario": "현재 스토리 장면 및 환경 설정",
  "char_detail_tab.label_first_mes": "첫 메시지 / 인사말 *",
  "char_detail_tab.placeholder_first_mes": "캐릭터의 오프닝 대사",
  "char_detail_tab.label_mes_example": "대화 예시",
  "char_detail_tab.placeholder_mes_example": "<user>: 누구세요?\n<char>: 저는...",
  "char_detail_tab.label_system_prompt": "커스텀 시스템 Prompt 덮어쓰기",
  "char_detail_tab.placeholder_system_prompt": "선택적 시스템 레벨 Prompt 덮어쓰기 규칙",

  "lore_editor.label_comment": "제목 또는 설명 *",
  "lore_editor.placeholder_comment": "예: 계약 마법, 숨겨진 성역",
  "lore_editor.label_keys": "트리거 키워드 (쉼표로 구분)",
  "lore_editor.placeholder_keys": "마법, 계약",
  "lore_editor.label_content": "로어 항목 콘텐츠 *",
  "lore_editor.placeholder_content": "구체적인 메모리 사실을 설명하세요...",
  "lore_editor.checkbox_regex": "정규식",
  "lore_editor.checkbox_memo": "메모 포함",
  "lore_editor.checkbox_constant": "상시",
  "lore_editor.checkbox_disabled": "이 항목 비활성화",
  "lore_editor.label_position": "위치",
  "lore_editor.position_after_char": "📌 캐릭터 정의 뒤",
  "lore_editor.position_before_char": "📌 캐릭터 정의 앞",
  "lore_editor.position_top": "📌 페이지 상단",
  "lore_editor.position_before_last": "💬 마지막 메시지 앞",
  "lore_editor.position_in_chat": "💬 기록 내 (깊이별)",
  "lore_editor.label_depth": "깊이",
  "lore_editor.label_order": "순서",
  "lore_editor.label_probability": "확률 (%)",
  "lore_editor.cancel": "취소",
  "lore_editor.save": "이 로어 항목 저장",

  "lorebook_tab.upgrade_title": "로어 항목 편집이 완전히 업그레이드되었습니다",
  "lorebook_tab.upgrade_desc": "이제 강력한 인플레이스 편집을 지원하여 현재 페이지를 떠나지 않고도 캐릭터별 로어 항목을 수정할 수 있습니다. 매칭 전략 선택, 동적 깊이 및 가중치 등 고급 기능은 하단 탭 '월드북' 독립 콘솔로 이동하는 것을 권장합니다.",
  "lorebook_tab.goto_worldbook": "🌐 하단 탭 '월드북' · 독립 다차원 콘솔로 바로 이동 ➡",
  "lorebook_tab.new_entry": "➕ 이 캐릭터의 커스텀 로어 항목 수동 추가 (인라인 생성기)",
  "lorebook_tab.new_entry_card_title": "✨ 이 캐릭터의 커스텀 로어 항목 빠르게 생성",
  "lorebook_tab.entry_list_title": "캐릭터별 로어 항목 ({count}개)",
  "lorebook_tab.unnamed_entry": "이름 없는 로어 항목",
  "lorebook_tab.badge_constant": "상시",
  "lorebook_tab.badge_disabled": "비활성화",
  "lorebook_tab.trigger_word_count": "({count}개 트리거 단어)",
  "lorebook_tab.meta_keys": "트리거 단어:",
  "lorebook_tab.meta_position": "위치:",
  "lorebook_tab.meta_depth_weight": "깊이 / 순서:",
  "lorebook_tab.meta_probability_regex": "확률 / 정규식:",
  "lorebook_tab.none": "(없음)",
  "lorebook_tab.position_after": "📌 캐릭터 뒤",
  "lorebook_tab.position_before": "📌 캐릭터 앞",
  "lorebook_tab.position_top": "📌 상단",
  "lorebook_tab.label_content": "로어 콘텐츠 (Prompt):",
  "lorebook_tab.label_memo": "⭐ 메모 포함",
  "lorebook_tab.edit_inline": "이 항목 편집 (인라인)",
  "lorebook_tab.confirm_delete": "이 로어 항목을 삭제하시겠습니까?",
  "lorebook_tab.delete": "삭제",
  "lorebook_tab.empty_state": "이 캐릭터 카드에는 아직 독립적으로 작성된 커스텀 로어 항목이 없습니다. 위의 버튼을 탭하여 추가하거나 하단 '공용 월드북' 채널을 사용하세요.",
  "regex.char_no_active": "선택되지 않음",
  "backup.collapse": "접기",
  "backup.expand": "펼치기",
  "backup.pass_placeholder": "잘 기억해 두세요. 그렇지 않으면 복구할 수 없습니다...",
  "chat_import.description": "시스템이 채팅 로그를 파싱하여 로컬 캐릭터 카드와 바인딩합니다. 해당 캐릭터 카드가 로컬에 가져와지지 않은 경우 먼저 가져오라는 메시지가 표시됩니다.",
  "chat_import.tip_label": "팁:",
  "chat_import.help_text": "가져오기 후 시스템은 API 대역폭 폭주를 방지하기 위해 기본적으로 이러한 과거 메시지의 자동 요약을 비활성화합니다.",
  "tts.test_text": "안녕하세요, 모바일 태번에 오신 것을 환영합니다. 이것은 TTS 테스트 읽기입니다.",
  "nav.chat": "채팅",
  "nav.playground": "샌드박스",
};

const fs = require('fs');
const path = require('path');

// Verify all en keys exist in koTranslations
const filePath = path.join(__dirname, 'src', 'locales', 'translations.ts');
const content = fs.readFileSync(filePath, 'utf8');

const enStart = content.indexOf('"en":');
const enEndTag = '  },\n  "ja":';
const enEndIdx = content.indexOf(enEndTag, enStart);
const enSectionRaw = content.substring(enStart, enEndIdx);

const lines = enSectionRaw.split('\n');
const enObj = {};
let capturingMultiline = false;
let multilineKey = '';
let multilineValue = '';

for (let i = 1; i < lines.length; i++) {
  const line = lines[i];
  const trimmed = line.trim();
  
  if (capturingMultiline) {
    multilineValue += ' ' + trimmed;
    if (trimmed.endsWith('",') || trimmed.endsWith('"')) {
      enObj[multilineKey] = multilineValue.replace(/^ /, '').replace(/"+[,;]?$/, '').replace(/^"/, '');
      capturingMultiline = false;
    }
    continue;
  }
  
  if (!trimmed || trimmed === '{' || trimmed === '},' || trimmed === '}') continue;
  
  const match = trimmed.match(/^"([^"]+)"\s*:\s*"(.+)",?$/);
  if (match) {
    const key = match[1];
    let value = match[2];
    if (value.endsWith('",')) value = value.slice(0, -2);
    else if (value.endsWith('"')) value = value.slice(0, -1);
    enObj[key] = value;
  } else {
    const partialMatch = trimmed.match(/^"([^"]+)"\s*:\s*"(.+)$/);
    if (partialMatch) {
      multilineKey = partialMatch[1];
      multilineValue = partialMatch[2];
      capturingMultiline = true;
      if (partialMatch[2].endsWith('",') || partialMatch[2].endsWith('"')) {
        enObj[multilineKey] = multilineValue.replace(/^ /, '').replace(/"+[,;]?$/, '').replace(/^"/, '');
        capturingMultiline = false;
      }
    }
  }
}

// Check for missing keys
const missingKeys = [];
for (const key of Object.keys(enObj)) {
  if (!(key in koTranslations)) {
    missingKeys.push(key);
  }
}

if (missingKeys.length > 0) {
  console.log('MISSING KEYS:');
  missingKeys.forEach(k => console.log(`  ${k}`));
}

// Check for extra keys
const extraKeys = [];
for (const key of Object.keys(koTranslations)) {
  if (!(key in enObj)) {
    extraKeys.push(key);
  }
}

if (extraKeys.length > 0) {
  console.log('EXTRA KEYS (not in en):');
  extraKeys.forEach(k => console.log(`  ${k}`));
}

console.log(`\nTotal en keys: ${Object.keys(enObj).length}`);
console.log(`Total ko translations: ${Object.keys(koTranslations).length}`);
console.log(`Missing: ${missingKeys.length}`);
console.log(`Extra: ${extraKeys.length}`);

if (missingKeys.length === 0 && extraKeys.length === 0) {
  module.exports = koTranslations;
} else {
  console.log('\nFix missing/extra keys before exporting.');
  process.exit(1);
}
