export interface LorebookEntry {
  id: string;
  keys: string[];       // Trigger keywords
  content: string;      // The actual worldbook lore
  constant: boolean;    // Always active in prompting context
  enabled: boolean;
  disabled?: boolean;   // Disabled toggle
  comment?: string;
  // Advanced fields
  useRegex?: boolean;   // Regex trigger
  addMemo?: boolean;    // Append comment as memo
  probability?: number; // Trigger probability (0-100, default 100)
  order?: number;       // Precedence order (default 100)
  position?: 'top' | 'before_char_def' | 'after_char_def' | 'before_last_mes'; // Physical insertion position
  depth?: number;       // Scan depth (how many of recent messages to inspect, default 4)
  isGlobal?: boolean;   // Whether this lorebook is global
}

export interface CharacterCard {
  id: string;
  name: string;
  avatar?: string;      // base64 image data URL
  description: string;  // Description of character
  personality: string;  // Personality definition
  scenario: string;     // Context scenario
  first_mes: string;    // First intro message
  mes_example: string;  // Dialogue examples
  system_prompt?: string;
  post_history_instructions?: string;
  alternate_greetings?: string[];
  lorebookEntries?: LorebookEntry[]; // Character-bound worldbook
}

export interface SummaryCard {
  id: string;
  timeTag: string;      // e.g. "第二天" (Day 2) or "深夜" (Late Night)
  location: string;     // e.g. "王都旅馆" (Royal Inn) or "林间空地" (Clearing)
  content: string;      // The compressed summary of the plot
}

export interface Message {
  id: string;
  sender: "user" | "assistant" | "system";
  content: string;
  timestamp: number;
  isSummaryLine?: boolean; // For inline marker
  generationTime?: number; // Time in seconds taken to generate the response
  tokenCount?: number;     // Tokens generated by the model
  promptTokenCount?: number; // Tokens sent in the prompt
}

export interface ChatSession {
  id: string;
  characterId: string;
  title: string;
  createdAt: number;
  messages: Message[];
  summaries: SummaryCard[]; // Timeline summaries
}

export type ApiType = "gemini-builtin" | "openai-compat";

export interface ApiConfig {
  type: ApiType;
  baseUrl: string;
  apiKey: string;
  modelName: string;
}

export interface SamplerPreset {
  id: string;
  name: string;
  temperature: number;
  topP: number;
  topK: number;
  repetitionPenalty: number;
  frequencyPenalty?: number;  // Advanced SillyTavern field
  presencePenalty?: number;   // Advanced SillyTavern field
  minP?: number;              // Advanced SillyTavern field
  maxTokens: number;
}

export interface MemoryConfig {
  recentTurns: number;          // Default e.g. 5
  summaryTriggerTurns: number;  // Default e.g. 15 (start summarizing when messages exceed this. 0 means follow recentTurns)
  summaryLength: number;        // Default e.g. 150 characters
}

export interface CustomPromptBlock {
  id: string;
  name: string;
  role: "system" | "user" | "assistant";
  content: string;
  enabled: boolean;
  identifier?: string;
  injection_order?: number;
}

export interface PromptConfig {
  mainPrompt: string;           // Global Main System Instruction
  jailbreakPrompt: string;      // Jailbreak text to reinforce/override filters
  useJailbreak: boolean;        // Toggle to turn jailbreak on/off
  postHistoryPrompt: string;    // Injected at the very end of history to coerce format
  usePostHistory: boolean;      // Toggle to turn post-history instructs on/off
  instructTemplate: "default" | "alpaca" | "chatml" | "llama3" | "custom";
  storyString?: string;         // SillyTavern STORY STRING context order templates
  customPrompts?: CustomPromptBlock[]; // SillyTavern customizable prompt block list
  
  // Custom templates if 'custom' is selected
  systemPrefix: string;
  systemSuffix: string;
  userPrefix: string;
  userSuffix: string;
  assistantPrefix: string;
  assistantSuffix: string;
}

export interface SavedPresetBundle {
  id: string;
  preset: SamplerPreset;
  promptConfig: PromptConfig;
}

export interface UserSettings {
  api: ApiConfig;
  preset: SamplerPreset;
  memory: MemoryConfig;
  promptConfig: PromptConfig;   // SillyTavern formatting controls
  userName: string;
  userAvatar?: string;
  savedPresets?: SavedPresetBundle[]; // Collection of saved multiple presets
}
