import type { CustomThemePackage } from "./utils/themePackage";
import type { PromptComposition, PromptCompositionTemplateRecord } from "./domain/prompt-composition";
import type { MessageContentPart } from "./domain/messages/messageContent";
import type { AgentCompositionSnapshot } from "./domain/agents/contracts";

export interface LorebookEntry {
  id: string;
  keys: string[]; // Trigger keywords
  secondary_keys?: string[]; // Secondary triggers
  selectiveLogic?: "AND_ANY" | "AND_ALL" | "NOT_ANY" | "NONE"; // Secondary keys logic
  caseSensitive?: boolean; // Case sensitive keyword matching
  content: string; // The actual worldbook lore
  constant: boolean; // Always active in prompting context
  enabled: boolean;
  disabled?: boolean; // Disabled toggle
  comment?: string;
  // Advanced fields
  useRegex?: boolean; // Regex trigger
  addMemo?: boolean; // Append comment as memo
  probability?: number; // Trigger probability (0-100, default 100)
  order?: number; // Precedence order (default 100)
  position?: "top" | "before_char_def" | "after_char_def" | "before_last_mes" | "in_chat"; // Physical insertion position
  depth?: number; // Insertion depth (0 = at the end, > 0 = deep into history)
  scanDepth?: number; // Scan depth (how many of recent messages to inspect, >= 0)
  isGlobal?: boolean; // Whether this lorebook is global
  /** 可选安全条件表达式；在关键词触发后根据 MVU 变量与会话状态二次过滤。 */
  condition?: string;
}

export interface CharacterVisualSettings {
  customCss?: string;
  bubbleColor?: string;
  bubbleTextColor?: string;
  userBubbleColor?: string;
  userBubbleTextColor?: string;
  primaryColor?: string;
  secondaryColor?: string;
  backgroundColor?: string;
  backgroundImageUrl?: string;
  backgroundOpacity?: number;
  backgroundBlur?: number;
  expressions?: any;
  enableAsteriskFormatting?: boolean;
  bgmUrl?: string;
  bgmVolume?: number;
}

export interface CharacterCard {
  id: string;
  /** 内置通用助手可声明为严格直连；缺省保持角色卡兼容行为。 */
  agentMode?: "direct-api";
  name: string;
  avatar?: string; // base64 image data URL
  description: string; // Description of character
  personality: string; // Personality definition
  scenario: string; // Context scenario
  first_mes: string; // First intro message
  mes_example: string; // Dialogue examples
  system_prompt?: string;
  post_history_instructions?: string;
  alternate_greetings?: string[];
  lorebookEntries?: LorebookEntry[]; // Character-bound worldbook
  isWorldbookGlobal?: boolean; // Whether the lorebook is universally evaluated
  creator?: string;               // Card creator
  creator_notes?: string;         // Card creator notes / usage guide
  tags?: string[];                // Character tags
  character_version?: string;     // Card version
  extensions?: Record<string, any>; // ST extensions or custom settings
  visualSettings?: CharacterVisualSettings; // Front-end cosmetic styling settings
  variables?: Record<string, any>; // Character persistent variables
}

export interface SummaryCard {
  id: string;
  timeTag: string; // e.g. "第二天" (Day 2) or "深夜" (Late Night)
  location: string; // e.g. "王都旅馆" (Royal Inn) or "林间空地" (Clearing)
  content: string; // The compressed summary of the plot
  condition?: string; // Character physical/mental condition
  inventory?: string; // Key items delta (acquired/lost)
  bonding?: string; // Relationship level/attitude change
  lastMessageId?: string; // Pointer to the last message summarized in this slice
}

export interface Message {
  id: string;
  sender: "user" | "assistant" | "system";
  content: string;
  /** V2 消息的唯一权威正文；`content` 仅为旧调用方使用的派生文本投影。 */
  parts?: MessageContentPart[];
  /** 缺失表示原始 V1 string 记录；值 2 表示 Content Parts 记录。 */
  contentVersion?: 2;
  timestamp: number;
  isSummaryLine?: boolean; // For inline marker
  generationTime?: number; // Time in seconds taken to generate the response
  tokenCount?: number; // Tokens generated by the model
  promptTokenCount?: number; // Tokens sent in the prompt
  reasoningContent?: string; // Reasoning content for thinking process
  swipes?: string[];
  swipe_id?: number;
  extra?: Record<string, any>;
  variables?: Record<string, any>;
  /** messages Store 中的绝对顺序；分页、分支与记忆边界统一使用该值。 */
  turnIndex?: number;
  /** 后台记忆抽取结果；消息重新水合后仍需保留，避免编辑等写回路径将其清空。 */
  tags?: string[];
  extractSource?: "llm" | "dict" | "none";
  /** `extra` 的持久化别名，仅用于兼容存储/备份边界。 */
  metadata?: Record<string, unknown>;
}

export interface ChatSession {
  id: string;
  characterId: string;
  title: string;
  createdAt: number;
  messages: Message[];
  summaries: SummaryCard[]; // Timeline summaries
  lastSummarizedMessageId?: string; // Tracks up to which message the summary has covered
  /** @deprecated 仅供旧会话读取迁移；新写入必须进入对应的 runtimePluginState 命名空间。 */
  variables?: Record<string, any>;
  tableMemory?: TableMemorySheet[]; // Structured memory sheets for stateful RP tracking
  pinnedMessageIds?: string[]; // IDs of messages explicitly pinned to recall list
  mutedMessageIds?: string[]; // IDs of messages muted from recall list
  turnCount?: number; // Cached count of turns (computed from user messages)
  charCount?: number; // Cached count of total characters in messages
  parentSessionId?: string; // Parent session ID if this session was branched
  parentMessageId?: string; // Message ID at which this session split off from parent
  /** 当前会话选择的 Prompt 场景方案；不修改全局预设。 */
  activePromptSceneProfileId?: string;
  /** 首次进入 Agent Spine 时冻结的安全组合快照；旧会话可缺失并在下一轮补写。 */
  compositionSnapshot?: AgentCompositionSnapshot;
  /** Runtime Plugin 私有状态命名空间；兼容期 `variables` 仍作为只读降级源。 */
  runtimePluginState?: Record<string, unknown>;
  /** 会话目录生命周期；旧记录读取时统一降级为 active。 */
  lifecycle?: "active" | "archived";
  /** 最近一次影响会话目录排序的权威活动时间。 */
  updatedAt?: number;
  /** 归档时间；仅 lifecycle=archived 时存在。 */
  archivedAt?: number;
  /** 指向独立收藏备份元数据，不承载备份正文。 */
  favoriteBackupId?: string;
  /** 影响恢复结果的持久化内容修订号。 */
  contentRevision?: number;
  /** 有限长度目录投影；消息正文仍以 messages Store 为准。 */
  lastMessagePreview?: string;
}

/** sessions Store 与界面会话目录共享的轻量会话信息，不包含消息窗口。 */
export type ChatSessionMetadata = Omit<ChatSession, "messages">;

/**
 * 只允许普通会话字段通过元数据更新路径修改。
 * 摘要、消息统计和消息内容各自拥有独立的原子事务，不能混入通用 patch。
 */
export type ChatSessionMetadataPatch = Partial<Omit<
  ChatSessionMetadata,
  "id" | "summaries" | "lastSummarizedMessageId" | "turnCount" | "charCount"
>>;

/** 当前会话已水合的消息窗口；虚拟列表只消费这里，不承担存储分页职责。 */
export interface ChatMessageWindow {
  sessionId: string;
  messages: Message[];
}

/** 当前活跃会话消息窗口的界面水合状态。 */
export type ChatMessageHydrationStatus = "idle" | "loading" | "ready" | "error";

export type ApiType = "openai-compat" | "openai" | "anthropic";

export interface ApiConfig {
  type: ApiType;
  baseUrl: string;
  apiKey: string;
  modelName: string;
  savedUrls?: string[];
  chatPath?: string;
  modelsPath?: string;
  bypassProxy?: boolean;
  sendNames?: boolean;
  disableReasoning?: boolean;
  forceBasicParams?: boolean;
  /** 用户确认当前模型/接口支持 OpenAI-compatible 图片输入；缺省按不支持处理。 */
  supportsVision?: boolean;
  /** 用户确认当前模型/接口支持 OpenAI-compatible input_audio；缺省按不支持处理。 */
  supportsAudioInput?: boolean;
  contextLimit?: number;
}

export interface SamplerPreset {
  id: string;
  name: string;
  temperature: number;
  topP: number;
  topK: number;
  repetitionPenalty: number;
  frequencyPenalty?: number; // Advanced SillyTavern field
  presencePenalty?: number; // Advanced SillyTavern field
  minP?: number; // Advanced SillyTavern field
  maxTokens: number;
}

export interface MemoryConfig {
  recentTurns: number; // Default e.g. 5
  summaryTriggerTurns: number; // Default e.g. 15 (start summarizing when messages exceed this. 0 means follow recentTurns)
  summaryLength: number; // Default e.g. 150 characters
  summarySystemPrompt?: string;
  timeTagTemplate?: string;
  enableAutoSummary?: boolean;
  enableRecall?: boolean;
  recallTopK?: number;
  /** 记忆召回超时保护（毫秒）。超时后跳过召回以保证首字响应速度。
   *  默认 3000ms；设为 0 表示禁用超时保护（始终等待召回完成）。 */
  recallTimeoutMs?: number;
}

export interface CustomPromptBlock {
  id: string;
  name: string;
  role: "system" | "user" | "assistant";
  content: string;
  enabled: boolean;
  identifier?: string;
  marker?: boolean;
  system_prompt?: boolean;
  injection_position?: number;
  injection_depth?: number;
  injection_order?: number;
  forbid_overrides?: boolean;
  injection_trigger?: string[];
}

/** 模型可返回的受约束原生选择项；不包含可执行动作或脚本。 */
export interface ReplyChoice {
  id: string;
  label: string;
  prompt: string;
  description?: string;
}

/**
 * 模型请求整形。该配置只描述通用 Chat Completions 消息语义，
 * 不承载 SillyTavern 脚本、DOM 或插件生命周期。
 */
export interface PromptRequestShapingConfig {
  enabled: boolean;
  /** 合并相邻且 role/name 相同的消息。 */
  mergeAdjacentMessages?: boolean;
  /** 将全部 system 消息合并到首条 system 消息。 */
  squashSystemMessages?: boolean;
  roleWrappers?: Partial<Record<"system" | "user" | "assistant", {
    prefix?: string;
    suffix?: string;
  }>>;
  /** 作为最后一条 assistant 消息发送的续写起始文本。 */
  assistantPrefill?: string;
  stopSequences?: string[];
}

export interface PromptConfig {
  roleplayMode?: boolean; // Whether to enable SillyTavern RP mode templates and jailbreaks
  mainPrompt: string; // Global Main System Instruction
  jailbreakPrompt: string; // Jailbreak text to reinforce/override filters
  useJailbreak: boolean; // Toggle to turn jailbreak on/off
  postHistoryPrompt?: string; // Injected at the very end of history to coerce format
  usePostHistory?: boolean; // Toggle to turn post-history instructs on/off
  instructTemplate: "default" | "alpaca" | "chatml" | "llama3" | "custom";
  storyString?: string; // SillyTavern STORY STRING context order templates
  customPrompts?: CustomPromptBlock[]; // SillyTavern customizable prompt block list
  useMainPrompt?: boolean;
  enableReasoningGuidance?: boolean;
  reasoningGuidancePrompt?: string;

  // Custom templates if 'custom' is selected
  systemPrefix: string;
  systemSuffix: string;
  userPrefix: string;
  userSuffix: string;
  assistantPrefix: string;
  assistantSuffix: string;

  sectionHeaders?: Record<string, string>;
  tableMemoryPrompt?: string;
  renderingFormat?: 'auto' | 'xml' | 'markdown';
  requestShaping?: PromptRequestShapingConfig;
  /** 新一代自由编排；关闭时保留旧 PromptService 路径作为迁移期回退。 */
  usePromptComposition?: boolean;
  composition?: PromptComposition;
}

export interface ApiProfile {
  id: string;
  name: string;
  type: "openai" | "anthropic" | "openai-compat";
  baseUrl: string;
  apiKey: string;
  modelName: string;
  chatPath?: string;
  modelsPath?: string;
  bypassProxy?: boolean;
  disableReasoning?: boolean;
  forceBasicParams?: boolean;
  supportsVision?: boolean;
  supportsAudioInput?: boolean;
}

/** 预设包中的传统 Prompt 字段；用于旧 Mobile Tavern 路径与兼容导出。 */
export type PresetPromptConfig = Omit<PromptConfig, "usePromptComposition" | "composition">;

export type PromptPresetPlanMode = "legacy" | "composition";
export type PromptPresetPlanSource = "mobile-tavern" | "sillytavern" | "native";

/**
 * 预设拥有的版本化 Prompt 运行快照。
 *
 * `mode` 明确决定加载预设后使用传统路径还是自由编排，避免旧预设缺字段时
 * 继承另一个预设的运行模式。`composition` 在 legacy 模式下也可作为待启用快照保留。
 */
export interface PromptPresetPlan {
  version: 1;
  mode: PromptPresetPlanMode;
  source: PromptPresetPlanSource;
  composition?: PromptComposition;
}

export interface SavedPresetBundle {
  id: string;
  preset: SamplerPreset;
  promptConfig: PresetPromptConfig;
  presetRegexScripts?: RegexScript[];
  /** 新数据的权威 Prompt 快照；旧数据由应用层从下方兼容字段迁移。 */
  promptPlan?: PromptPresetPlan;
  /**
   * @deprecated 旧版 Prompt 快照字段，仅用于无损读取历史数据。
   * 新保存以 `promptPlan` 为准。
   */
  composition?: PromptComposition;
  /** @deprecated 旧版运行模式字段，仅用于无损读取历史数据。 */
  usePromptComposition?: boolean;
  /**
   * 是否为内置（随应用出厂）预设。内置预设由启动加载器强制重建，不可删除；
   * 导入或另存为副本的预设不带此标记。旧数据缺省视为非内置（导入/自定义）。
   */
  isBuiltin?: boolean;
}

export interface UserPersona {
  id: string;
  name: string;
  avatar?: string;
  description?: string;
}

export type CompatibilityScriptSecurityMode = "isolated" | "trusted";

export interface UserSettings {
  api: ApiConfig;
  preset: SamplerPreset;
  memory: MemoryConfig;
  promptConfig: PromptConfig; // SillyTavern formatting controls
  promptCompositionTemplates?: PromptCompositionTemplateRecord[];
  userName: string;
  userInfo?: string;
  userAvatar?: string;
  userPersonas?: UserPersona[];
  activePersonaId?: string;
  savedPresets?: SavedPresetBundle[]; // Collection of saved multiple presets
  enableHtmlRendering?: boolean; // Render exact HTML/CSS from AI output
  expressionTriggers?: Record<string, string>;
  hasInjectedFormatPreset?: boolean; // Track if the format preservation preset has been injected
  enableScriptExecution?: boolean; // Toggle to execute custom interactive iframe scripts
  /**
   * isolated：opaque-origin iframe + 最小 postMessage bridge；
   * trusted：保留旧 SillyTavern 同源父窗口兼容能力，仅用于明确受信角色卡。
   */
  scriptSecurityMode?: CompatibilityScriptSecurityMode;
  enableLoopProtection?: boolean; // Protect main thread from infinite script loops
  variables?: Record<string, any>; // Persistent global variables for TavernHelper compatibility
  extensionSettings?: Record<string, any>; // Persistent settings for SillyTavern extensions compatibility
  hasInitializedDefaultCharacters?: boolean; // Track if the built-in characters have been initialized
  globalChatBg?: string; // Global default chat background (base64 image URL)
  chatBackgroundBlur?: number; // Background blur radius in pixels
  chatBackgroundDim?: number; // Background overlay dim percentage (0-100)
  enableChatBgAnimation?: boolean; // Whether to enable Ken Burns animation
  savedApiProfiles?: ApiProfile[];
  currentApiProfileId?: string;
  globalRegexScripts?: RegexScript[];
  presetRegexScripts?: RegexScript[];
  enableTableMemory?: boolean; // Enable memory table enhancement
  tableMemoryCheckFrequency?: number; // Frequency to let AI check and update memory (e.g. 1 turn, 3 turns)
  enableEmotionAmbientGlow?: boolean; // Enable emotion-reactive ambient lighting
  enableReplySuggestions?: boolean; // Enable suggested action options
  replySuggestionsClickMode?: "send" | "fill"; // Default action on suggestion click
  enableBisonMode?: boolean; // Enable Bison Mode
  enableReasoningContentDisplay?: boolean; // Display reasoning content (thinking chain) in chat bubbles. Default: true
  replySuggestionsPrompt?: string; // Suggestions prompt template
  bisonModePrompt?: string; // Bison Mode prompt template
  enableMultiMessageQueue?: boolean; // Enable Multi-Message Queue and merge sending
  enableAsteriskFormatting?: boolean; // Global fallback: render *action* text as grey italic (overridden by per-card visualSettings)
  imageGenApi?: ImageGenApiConfig; // 独立的生图 API 配置
  chatFontSize?: number; // Chat bubble font size in px
  chatLineHeight?: number; // Chat bubble line height (multiplier)
  ttsConfig?: TtsConfig; // TTS 朗读配置
  asrConfig?: AsrConfig; // ASR 语音输入配置
  lastBackupTime?: number; // 上次成功执行每日自动备份的时间戳
  customThemes?: CustomThemePackage[]; // 已导入的自定义主题包列表（.tavern-theme.json）
  hiddenMainTabs?: string[]; // 仅隐藏底栏入口；角色与设置为恢复入口，不能隐藏
  themeMediaEnabled?: boolean; // 用户明确允许主题播放本地音视频；默认关闭
  enableFloatingCharacter?: boolean; // 启用应用内悬浮角色助手（显示当前角色立绘 + 情绪 + 聊天气泡）
}

export interface ImageGenApiConfig {
  enabled: boolean;
  type: "openai-dalle" | "sd-webui" | "novelai";
  baseUrl: string;
  apiKey: string;
  modelName: string;
  promptPrefix: string;
  negativePrompt: string;
  width: number;
  height: number;
  steps: number;
  cfgScale: number;
  sampler: string;
  promptGeneratorTemplate?: string; // 生成生图提示词的引导模板
  promptEditBeforeGenerate?: boolean; // 是否在生图前弹窗编辑提示词
  forceProtocol?: boolean; // 是否强行指定接口协议，默认不开启（即开启自动识别 / openai-dalle 降级）
}

export interface TtsConfig {
  enabled: boolean;
  provider: "speech-synthesis" | "openai";
  volume: number; // 0 到 1 之间
  rate: number;   // 语速 0.1 到 10 之间
  pitch: number;  // 音高 0 到 2 之间
  voiceName?: string; // Web Speech API 声音名称
  openaiApiKey?: string;
  openaiBaseUrl?: string;
  openaiModel?: string; // tts-1, tts-1-hd 等
  openaiVoice?: string; // alloy, echo, fable, onyx, nova, shimmer
  readMode?: "all" | "dialogue_only";
  playMode?: "auto" | "manual";
}

export interface RegexScript {
  id: string;
  scriptName: string;
  findRegex: string; // Regexp pattern e.g. /pattern/flags
  replaceString: string; // Substitution text
  disabled: boolean; // Enabled toggle
  placement: number[]; // e.g. [1, 2] (1 = input, 2 = output)
  runOnEdit?: boolean;
  markdownOnly?: boolean;
  promptOnly?: boolean;
  substituteRegex?: number;
  minDepth?: number | null;
  maxDepth?: number | null;
  trimStrings?: string[];
}

export type TableMemoryColumnType = "text" | "number" | "date" | "enum";

/**
 * 状态表列的高阶 Schema。`id` 在列重命名时保持稳定，用于迁移旧行数据；
 * `columns` 仍作为兼容字段保留，旧会话缺少本字段时按 text 类型降级。
 */
export interface TableMemoryColumnDefinition {
  id: string;
  name: string;
  type: TableMemoryColumnType;
  defaultValue?: string;
  enumOptions?: string[];
}

export interface TableMemorySheet {
  id: string;          // Unique Sheet ID
  name: string;        // Sheet name (e.g. "人物属性", "好感关系", "背包状态")
  columns: string[];   // Column names (e.g. ["角色", "好感值", "备注"])
  columnDefinitions?: TableMemoryColumnDefinition[]; // Typed schema metadata (backward compatible)
  rows: string[][];    // 2D grid of values
  enable: boolean;     // Whether to inject to AI context
  description?: string;// Guide for the AI (e.g. "用于记录玩家和你的好感阶段")
}

export interface CustomWorldbook {
  id: string;
  name: string;
  entries: LorebookEntry[];
  enabled: boolean;
}

export interface AsrConfig {
  enabled: boolean;
  provider: "web-speech" | "openai";
  language: string;
  openaiApiKey?: string;
  openaiBaseUrl?: string;
  openaiModel?: string;
}
