export interface LorebookEntry {
  id: string;
  keys: string[]; // Trigger keywords
  secondary_keys?: string[]; // Secondary triggers
  selectiveLogic?: "AND_ANY" | "AND_ALL" | "NOT_ANY" | "NONE"; // Secondary keys logic
  caseSensitive?: boolean; // Case sensitive keyword matching
  content: string; // The actual worldbook lore
  constant: boolean; // Always active in prompting context
  enabled: boolean;
  disabled?: boolean; // Disabled toggle
  comment?: string;
  // Advanced fields
  useRegex?: boolean; // Regex trigger
  addMemo?: boolean; // Append comment as memo
  probability?: number; // Trigger probability (0-100, default 100)
  order?: number; // Precedence order (default 100)
  position?: "top" | "before_char_def" | "after_char_def" | "before_last_mes" | "in_chat"; // Physical insertion position
  depth?: number; // Insertion depth (0 = at the end, > 0 = deep into history)
  scanDepth?: number; // Scan depth (how many of recent messages to inspect, >= 0)
  isGlobal?: boolean; // Whether this lorebook is global
}

export interface CharacterVisualSettings {
  customCss?: string;
  bubbleColor?: string;
  bubbleTextColor?: string;
  userBubbleColor?: string;
  userBubbleTextColor?: string;
  primaryColor?: string;
  secondaryColor?: string;
  backgroundColor?: string;
  backgroundImageUrl?: string;
  backgroundOpacity?: number;
  backgroundBlur?: number;
  expressions?: any;
  enableAsteriskFormatting?: boolean;
}

export interface CharacterCard {
  id: string;
  name: string;
  avatar?: string; // base64 image data URL
  description: string; // Description of character
  personality: string; // Personality definition
  scenario: string; // Context scenario
  first_mes: string; // First intro message
  mes_example: string; // Dialogue examples
  system_prompt?: string;
  post_history_instructions?: string;
  alternate_greetings?: string[];
  lorebookEntries?: LorebookEntry[]; // Character-bound worldbook
  isWorldbookGlobal?: boolean; // Whether the lorebook is universally evaluated
  creator?: string;               // Card creator
  creator_notes?: string;         // Card creator notes / usage guide
  tags?: string[];                // Character tags
  character_version?: string;     // Card version
  extensions?: Record<string, any>; // ST extensions or custom settings
  visualSettings?: CharacterVisualSettings; // Front-end cosmetic styling settings
  variables?: Record<string, any>; // Character persistent variables
}

export interface SummaryCard {
  id: string;
  timeTag: string; // e.g. "第二天" (Day 2) or "深夜" (Late Night)
  location: string; // e.g. "王都旅馆" (Royal Inn) or "林间空地" (Clearing)
  content: string; // The compressed summary of the plot
  condition?: string; // Character physical/mental condition
  inventory?: string; // Key items delta (acquired/lost)
  bonding?: string; // Relationship level/attitude change
  lastMessageId?: string; // Pointer to the last message summarized in this slice
}

export interface Message {
  id: string;
  sender: "user" | "assistant" | "system";
  content: string;
  timestamp: number;
  isSummaryLine?: boolean; // For inline marker
  generationTime?: number; // Time in seconds taken to generate the response
  tokenCount?: number; // Tokens generated by the model
  promptTokenCount?: number; // Tokens sent in the prompt
  reasoningContent?: string; // Reasoning content for thinking process
  swipes?: string[];
  swipe_id?: number;
  extra?: Record<string, any>;
  variables?: Record<string, any>;
}

export interface ChatSession {
  id: string;
  characterId: string;
  title: string;
  createdAt: number;
  messages: Message[];
  summaries: SummaryCard[]; // Timeline summaries
  lastSummarizedMessageId?: string; // Tracks up to which message the summary has covered
  variables?: Record<string, any>; // Chat session local variables
  tableMemory?: TableMemorySheet[]; // Structured memory sheets for stateful RP tracking
  pinnedMessageIds?: string[]; // IDs of messages explicitly pinned to recall list
  mutedMessageIds?: string[]; // IDs of messages muted from recall list
}

export type ApiType = "openai-compat" | "openai" | "anthropic";

export interface ApiConfig {
  type: ApiType;
  baseUrl: string;
  apiKey: string;
  modelName: string;
  savedUrls?: string[];
  chatPath?: string;
  modelsPath?: string;
  bypassProxy?: boolean;
  sendNames?: boolean;
  disableReasoning?: boolean;
  forceBasicParams?: boolean;
}

export interface SamplerPreset {
  id: string;
  name: string;
  temperature: number;
  topP: number;
  topK: number;
  repetitionPenalty: number;
  frequencyPenalty?: number; // Advanced SillyTavern field
  presencePenalty?: number; // Advanced SillyTavern field
  minP?: number; // Advanced SillyTavern field
  maxTokens: number;
}

export interface MemoryConfig {
  recentTurns: number; // Default e.g. 5
  summaryTriggerTurns: number; // Default e.g. 15 (start summarizing when messages exceed this. 0 means follow recentTurns)
  summaryLength: number; // Default e.g. 150 characters
  summarySystemPrompt?: string;
  timeTagTemplate?: string;
}

export interface CustomPromptBlock {
  id: string;
  name: string;
  role: "system" | "user" | "assistant";
  content: string;
  enabled: boolean;
  identifier?: string;
  injection_order?: number;
}

export interface PromptConfig {
  roleplayMode?: boolean; // Whether to enable SillyTavern RP mode templates and jailbreaks
  mainPrompt: string; // Global Main System Instruction
  jailbreakPrompt: string; // Jailbreak text to reinforce/override filters
  useJailbreak: boolean; // Toggle to turn jailbreak on/off
  postHistoryPrompt?: string; // Injected at the very end of history to coerce format
  usePostHistory?: boolean; // Toggle to turn post-history instructs on/off
  instructTemplate: "default" | "alpaca" | "chatml" | "llama3" | "custom";
  storyString?: string; // SillyTavern STORY STRING context order templates
  customPrompts?: CustomPromptBlock[]; // SillyTavern customizable prompt block list
  useMainPrompt?: boolean;
  enableReasoningGuidance?: boolean;
  reasoningGuidancePrompt?: string;

  // Custom templates if 'custom' is selected
  systemPrefix: string;
  systemSuffix: string;
  userPrefix: string;
  userSuffix: string;
  assistantPrefix: string;
  assistantSuffix: string;

  sectionHeaders?: Record<string, string>;
  tableMemoryPrompt?: string;
}

export interface ApiProfile {
  id: string;
  name: string;
  type: "openai" | "anthropic" | "openai-compat";
  baseUrl: string;
  apiKey: string;
  modelName: string;
  chatPath?: string;
  modelsPath?: string;
  bypassProxy?: boolean;
  disableReasoning?: boolean;
  forceBasicParams?: boolean;
}

export interface SavedPresetBundle {
  id: string;
  preset: SamplerPreset;
  promptConfig: PromptConfig;
  presetRegexScripts?: RegexScript[];
}

export interface UserPersona {
  id: string;
  name: string;
  avatar?: string;
  description?: string;
}

export interface UserSettings {
  api: ApiConfig;
  preset: SamplerPreset;
  memory: MemoryConfig;
  promptConfig: PromptConfig; // SillyTavern formatting controls
  userName: string;
  userInfo?: string;
  userAvatar?: string;
  userPersonas?: UserPersona[];
  activePersonaId?: string;
  savedPresets?: SavedPresetBundle[]; // Collection of saved multiple presets
  enableHtmlRendering?: boolean; // Render exact HTML/CSS from AI output
  expressionTriggers?: Record<string, string>;
  hasInjectedFormatPreset?: boolean; // Track if the format preservation preset has been injected
  enableScriptExecution?: boolean; // Toggle to execute custom interactive iframe scripts
  variables?: Record<string, any>; // Persistent global variables for TavernHelper compatibility
  extensionSettings?: Record<string, any>; // Persistent settings for SillyTavern extensions compatibility
  hasInitializedDefaultCharacters?: boolean; // Track if the built-in characters have been initialized
  globalChatBg?: string; // Global default chat background (base64 image URL)
  chatBackgroundBlur?: number; // Background blur radius in pixels
  chatBackgroundDim?: number; // Background overlay dim percentage (0-100)
  enableChatBgAnimation?: boolean; // Whether to enable Ken Burns animation
  savedApiProfiles?: ApiProfile[];
  currentApiProfileId?: string;
  globalRegexScripts?: RegexScript[];
  presetRegexScripts?: RegexScript[];
  enableTableMemory?: boolean; // Enable memory table enhancement
  tableMemoryCheckFrequency?: number; // Frequency to let AI check and update memory (e.g. 1 turn, 3 turns)
  enableEmotionAmbientGlow?: boolean; // Enable emotion-reactive ambient lighting
  enableReplySuggestions?: boolean; // Enable suggested action options
  replySuggestionsClickMode?: "send" | "fill"; // Default action on suggestion click
  enableBisonMode?: boolean; // Enable Bison Mode
  enableReasoningContentDisplay?: boolean; // Display reasoning content (thinking chain) in chat bubbles. Default: true
  replySuggestionsPrompt?: string; // Suggestions prompt template
  bisonModePrompt?: string; // Bison Mode prompt template
  enableMultiMessageQueue?: boolean; // Enable Multi-Message Queue and merge sending
  enableAsteriskFormatting?: boolean; // Global fallback: render *action* text as grey italic (overridden by per-card visualSettings)
  imageGenApi?: ImageGenApiConfig; // 独立的生图 API 配置
}

export interface ImageGenApiConfig {
  enabled: boolean;
  type: "openai-dalle" | "sd-webui" | "novelai";
  baseUrl: string;
  apiKey: string;
  modelName: string;
  promptPrefix: string;
  negativePrompt: string;
  width: number;
  height: number;
  steps: number;
  cfgScale: number;
  sampler: string;
  promptGeneratorTemplate?: string; // 生成生图提示词的引导模板
  promptEditBeforeGenerate?: boolean; // 是否在生图前弹窗编辑提示词
  forceProtocol?: boolean; // 是否强行指定接口协议，默认不开启（即开启自动识别 / openai-dalle 降级）
}

export interface RegexScript {
  id: string;
  scriptName: string;
  findRegex: string; // Regexp pattern e.g. /pattern/flags
  replaceString: string; // Substitution text
  disabled: boolean; // Enabled toggle
  placement: number[]; // e.g. [1, 2] (1 = input, 2 = output)
  runOnEdit?: boolean;
  markdownOnly?: boolean;
  promptOnly?: boolean;
}

export interface TableMemorySheet {
  id: string;          // Unique Sheet ID
  name: string;        // Sheet name (e.g. "人物属性", "好感关系", "背包状态")
  columns: string[];   // Column names (e.g. ["角色", "好感值", "备注"])
  rows: string[][];    // 2D grid of values
  enable: boolean;     // Whether to inject to AI context
  description?: string;// Guide for the AI (e.g. "用于记录玩家和你的好感阶段")
}

export interface CustomWorldbook {
  id: string;
  name: string;
  entries: LorebookEntry[];
  enabled: boolean;
}


