name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**" # 仅当 docs 目录下的文件发生变动时才触发构建与部署

env:
  TZ: Asia/Shanghai

# 设置 GITHUB_TOKEN 权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 保证同一时间只有一个部署任务在运行
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs' # 指定部署 docs 目录下的静态网页文件

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
